components:
  schemas:
    AMLLockSanctionInquiryRequest:
            type: object
            properties:
              Msg_Data:
                type: object
                properties:
                  Body:
                    type: object
                    description: Business request payload specific to the service operation
                    properties:
                      Addrss:
                        type: string
                      Ath_Prsns:
                        type: string
                      Bnfcry_Bnk_BIC_Cd:
                        type: string
                      Bnfcry_Bnk_Nm:
                        type: string
                      Bnfcry_CIF:
                        type: string
                      Bnfcry_Cntry:
                        type: string
                      Bnfcry_Cust_Nm_Ar:
                        type: string
                      Bnfcry_Cust_Nm_En:
                        type: string
                      Bnfcry_ID_No:
                        type: string
                      Bnfcry_Ntnlty:
                        type: string
                      Cust_ID_No:
                        type: string
                      Cust_Mbl_No:
                        type: string
                      Cust_Nm_Ar:
                        type: string
                      Cust_Nm_En:
                        type: string
                      Incmng_Otgng_Trnsctn:
                        type: string
                      Intrmdt_Bnk_Nm:
                        type: string
                      Mngrs:
                        type: string
                      Ntnlty:
                        type: string
                      Ownrs:
                        type: string
                      Rmttr_Bnk_BIC_Cd:
                        type: string
                      Rmttr_Bnk_Nm:
                        type: string
                      Rqstd_Actn:
                        type: string
                      Trnsctn_Amt:
                        type: string
                      Trnsctn_Cry:
                        type: string
                      Usr_Dfnd_1:
                        type: string
                      Usr_Dfnd_3:
                        type: string
                      Usr_Dfnd_4:
                        type: string
                      Usr_Dfnd_5:
                        type: string
                      Usr_Dfnd_6:
                        type: string
                    additionalProperties: false
                  EAIHeader:
                    type: object
                    description: Technical and routing metadata required for request processing and tracking
                    properties:
                      CIF:
                        type: string
                      ChnlId:
                        type: string
                      EAIRtrnCd:
                        type: string
                      FE_Ref_No:
                        type: string
                      FunctnId:
                        type: string
                      Lang:
                        type: string
                      MsgFrmt:
                        type: string
                      Rqstr_Info1:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info2:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info3:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info4:
                        type: string
                        description: Additional requester-provided metadata field
                      UsrDfn:
                        type: string
                    additionalProperties: false
                additionalProperties: false
            additionalProperties: false
    AMLLockSanctionInquiryResponse:
      properties:
        data:
          $ref: '#/components/schemas/AMLLockSanctionInquiryResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    AMLLockSanctionInquiryResponseData:
      description: Response data payload - customize per operation
      type: object
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            description: Response code
            type: string
          info:
            description: Response message
            type: string
        type: object
      type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: AML Lock Sanction Inquiry
  version: 1.0.0
  x-ibm-name: aml-lock-sanction-inquiry
openapi: 3.0.0
paths:
  /aml-lock-sanction-inquiry:
    post:
      operationId: AMLLockSanctionInquiry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AMLLockSanctionInquiryRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AMLLockSanctionInquiryResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - AMLLockSanctionInquiry
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://aml-lock-http-bab-sit-cp4i.apps.babsitaro.albtests.com/AMLLock_Snctn_Inqry
  testable: true
  type: rest
