components:
  schemas:
    BIBAccountSummaryDetailsRequest:
            type: object
            properties:
              data:
                type: object
                description: Business request payload for account summary details inquiry
                properties:
                  accountNumber:
                    type: string
                  pageOffset:
                    type: string
                  pageSize:
                    type: string
                additionalProperties: false
              header:
                type: object
                description: Technical and routing metadata required for request processing and tracking
                properties:
                  backendReferenceNumber:
                    type: string
                  channelId:
                    type: string
                  cif:
                    type: string
                  deviceInfo:
                    type: object
                    description: Device information for the request
                    properties:
                      city:
                        type: string
                      country:
                        type: string
                      id:
                        type: string
                      ipAddress:
                        type: string
                      model:
                        type: string
                      osVersion:
                        type: string
                    additionalProperties: false
                  eaiReturnCode:
                    type: string
                  frontendReferenceNumber:
                    type: string
                  functionId:
                    type: string
                  language:
                    type: string
                  messageFormat:
                    type: string
                  originalMessageId:
                    type: string
                  requesterInformation1:
                    type: string
                    description: Additional requester-provided metadata field
                  requesterInformation14:
                    type: string
                    description: Additional requester-provided metadata field
                  requesterInformation19:
                    type: string
                    description: Additional requester-provided metadata field
                  requesterInformation2:
                    type: string
                    description: Additional requester-provided metadata field
                  requesterInformation3:
                    type: string
                    description: Additional requester-provided metadata field
                  requesterInformation5:
                    type: string
                    description: Additional requester-provided metadata field
                  requesterInformation6:
                    type: string
                    description: Additional requester-provided metadata field
                  requesterInformation7:
                    type: string
                    description: Additional requester-provided metadata field
                  reversalOption:
                    type: string
                  timeStamp:
                    type: string
                additionalProperties: false
            additionalProperties: false
    BIBAccountSummaryDetailsResponse:
      properties:
        data:
          $ref: '#/components/schemas/BIBAccountSummaryDetailsResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    BIBAccountSummaryDetailsResponseData:
      description: Response data payload - customize per operation
      type: object
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            description: Response code
            type: string
          info:
            description: Response message
            type: string
        type: object
      type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: BIB Account Summary Details
  version: 1.0.0
  x-ibm-name: bib-account-summary-details
openapi: 3.0.0
paths:
  /bib-account-summary-details:
    post:
      operationId: BIBAccountSummaryDetails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BIBAccountSummaryDetailsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BIBAccountSummaryDetailsResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - BIBAccountSummaryDetails
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://bib-services-http-bab-sit-cp4i.apps.babsitaro.albtests.com/bib/accountsummarydetails
  testable: true
  type: rest
