components:
  schemas:
    CheckAntiFraudRulesRequest:
      additionalProperties: false
      properties:
        EAIMessage:
          additionalProperties: false
          description: Enterprise Application Integration envelope containing header metadata and business payload
          properties:
            Body:
              additionalProperties: false
              description: Business request payload specific to the service operation
              properties:
                Agnt:
                  type: string
                Asst_Tp:
                  type: string
                Blln_Pymnt:
                  type: string
                Chnl_Id:
                  type: string
                Chrg_Fees:
                  additionalProperties: false
                  properties:
                    Chrg_Fee:
                      items:
                        additionalProperties: false
                        properties:
                          Chrg_Amt:
                            type: string
                          Chrg_Cd:
                            type: string
                          Chrg_Pymnt_Tp:
                            type: string
                        type: object
                      type: array
                  type: object
                Chrg_Liq_Acct:
                  type: string
                Clndr:
                  type: string
                Cust_Age:
                  type: string
                Cust_Dprtmnt:
                  type: string
                Cust_Emplymnt_Dt:
                  type: string
                Cust_Emplyr:
                  type: string
                Cust_Emplyr_Phn_No:
                  type: string
                Cust_Occptn:
                  type: string
                Cust_Slry:
                  type: string
                DBR_Prcnt:
                  type: string
                Dl_Tp:
                  type: string
                Dwn_Pymnnt_VAT:
                  type: string
                Dwn_Pymnt:
                  type: string
                Dwn_Pymnt_Bnk:
                  type: string
                Flat_Rate:
                  type: string
                Fnl_Mtrty_Dt:
                  type: string
                Insrnc_Amt:
                  type: string
                Insrnc_Amt_Wth_VAT:
                  type: string
                Insrnc_Dscnt:
                  type: string
                Insrnc_Frst_Prm:
                  type: string
                Instllmnt_Day:
                  type: string
                Invc_Amt:
                  type: string
                Invc_Amt_Rcvd:
                  type: string
                Loan_Amt:
                  type: string
                Loan_ID:
                  type: string
                Loan_Ref:
                  type: string
                Mngt_Prcnt:
                  type: string
                Prft_Insrnc_Pymnt:
                  type: string
                Prft_Liq_Acct:
                  type: string
                Prncpl_Liq_Acct:
                  type: string
                Pymnt_Optn:
                  type: string
                Rbt_Amt:
                  type: string
                Rbt_In_PO:
                  type: string
                Rbt_Mgnt_Amt:
                  type: string
                Rbt_Mgnt_Vat_Amt:
                  type: string
                Rbt_Prcnt:
                  type: string
                Rcvr_Cst:
                  type: string
                Slry_Trnsfr:
                  type: string
                Srv_Prd:
                  type: string
                Tenor:
                  type: string
              type: object
            EAIHeader:
              additionalProperties: false
              description: Technical and routing metadata required for request processing and tracking
              properties:
                CIF:
                  type: string
                ChnlId:
                  type: string
                FE_Ref_No:
                  type: string
                FunctnId:
                  type: string
                Lang:
                  type: string
                MsgFrmt:
                  type: string
                Rqstr_Info1:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info2:
                  description: Additional requester-provided metadata field
                  type: string
                RvrslOptn:
                  type: string
                Tmstmp:
                  type: string
              type: object
          type: object
      type: object
    CheckAntiFraudRulesRequestData:
      type: object
    CheckAntiFraudRulesResponse:
      properties:
        data:
          $ref: '#/components/schemas/CheckAntiFraudRulesResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    CheckAntiFraudRulesResponseData:
      type: object
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
        - $ref: '#/components/schemas/RequestHeader'
        - properties:
            code:
              type: string
            info:
              type: string
          type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: Check Anti Fraud Rules
  version: 1.0.0
  x-ibm-name: check-anti-fraud-rules
openapi: 3.0.0
paths:
  /check-anti-fraud-rules:
    post:
      operationId: CheckAntiFraudRules
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckAntiFraudRulesRequest'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckAntiFraudRulesResponse'
          description: success
security:
  - clientID: []
    clientSecret: []
  - oAuth:
      - Integration_scope
servers:
  - url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
      - operation-switch:
          case:
            - execute:
                - invoke:
                    backend-type: json
                    chunked-uploads: true
                    follow-redirects: false
                    header-control:
                      type: blocklist
                      values: []
                    inject-proxy-headers: true
                    parameter-control:
                      type: allowlist
                      values: []
                    persistent-connection: true
                    target-url: $(target-url)
                    timeout: 60
                    title: invoke
                    verb: POST
                    version: 2.0.0
              operations:
                - CheckAntiFraudRules
          otherwise: []
          title: operation-switch
          version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://check-anti-fraud-rules-http-bab-sit-cp4i.apps.babsitaro.albtests.com/CheckAntiFraudRules
  testable: true
  type: rest
