components:
  schemas:
    CreateInvestmentAccountRequest:
            type: object
            properties:
              InvestorAccountReq:
                type: object
                properties:
                  CustomerDetail:
                    type: object
                    properties:
                      ArabicCity:
                        type: string
                      BuildingNo:
                        type: string
                      CIF:
                        type: string
                      CashAccounts:
                        type: string
                      City:
                        type: string
                      Country:
                        type: string
                      CustomerGroup:
                        type: string
                      DOBGregorian:
                        type: string
                      DOBHijri:
                        type: string
                      District:
                        type: string
                      Email:
                        type: string
                      ExpiryDate:
                        type: string
                      ExpiryDateHijri:
                        type: string
                      ExternalReference:
                        type: string
                      FamilyNameAR:
                        type: string
                      FamilyNameEN:
                        type: string
                      FirstNameAR:
                        type: string
                      FirstNameEN:
                        type: string
                      Gender:
                        type: string
                      IdNumber:
                        type: string
                      IdType:
                        type: string
                      MailAddressType:
                        type: string
                      MaritalStatus:
                        type: string
                      Mobile:
                        type: string
                      Nationality:
                        type: string
                      Occupation:
                        type: string
                      PoBox:
                        type: string
                      PreferedLanguage:
                        type: string
                      RelationshipManager:
                        type: string
                      SecondNameAR:
                        type: string
                      SecondNameEN:
                        type: string
                      Sector:
                        type: string
                      Segment:
                        type: string
                      StreetName:
                        type: string
                      WASELAdditionalCode:
                        type: string
                      WASELBuildingNo:
                        type: string
                      WASELDistrict:
                        type: string
                      WASELUnitNo:
                        type: string
                      WASELZipCode:
                        type: string
                      ZIP:
                        type: string
                    additionalProperties: false
                  Header:
                    type: object
                    properties:
                      FragmentID:
                        type: string
                      IsLast:
                        type: string
                      ReturnCode:
                        type: string
                      TimeStamp:
                        type: string
                    additionalProperties: false
                  TransactionID:
                    type: string
                additionalProperties: false
            additionalProperties: false
    CreateInvestmentAccountRequestData:
      type: object
    CreateInvestmentAccountResponse:
      properties:
        data:
          $ref: '#/components/schemas/CreateInvestmentAccountResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    CreateInvestmentAccountResponseData:
      type: object
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            type: string
          info:
            type: string
        type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: Create Investment Account
  version: 1.0.0
  x-ibm-name: create-investment-account
openapi: 3.0.0
paths:
  /create-investment-account:
    post:
      operationId: CreateInvestmentAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInvestmentAccountRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateInvestmentAccountResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - CreateInvestmentAccount
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://create-investment-account-http-bab-sit-cp4i.apps.babsitaro.albtests.com/CreateInvestmentAccount
  testable: true
  type: rest
