components:
  schemas:
    GetAccountTransactionsListRequest:
      additionalProperties: false
      properties:
        EAIMessage:
          additionalProperties: false
          description: Enterprise Application Integration envelope containing header metadata and business payload
          properties:
            Body:
              additionalProperties: false
              description: Business request payload specific to the service operation
              properties:
                Acct_No:
                  type: string
                Acct_Tp:
                  type: string
                Card_No:
                  type: string
                From_Dt:
                  type: string
                Last_N_Trxs:
                  type: string
                Mode:
                  type: string
                Portfolio_No:
                  type: string
                Rqst_Id:
                  type: string
                Src_Sys:
                  type: string
                Tmstmp:
                  type: string
                To_Dt:
                  type: string
                Trx_Ref_No:
                  type: string
                Trx_Tp:
                  type: string
                VAT_Stmnt:
                  type: string
              type: object
            EAIHeader:
              additionalProperties: false
              description: Technical and routing metadata required for request processing and tracking
              properties:
                BE_Ref_No:
                  type: string
                CIF:
                  type: string
                ChnlId:
                  type: string
                EAIRtrnCd:
                  type: string
                FE_Ref_No:
                  type: string
                FunctnId:
                  type: string
                Lang:
                  type: string
                MsgFrmt:
                  type: string
                OrgnlMsgId:
                  type: string
                Rqstr_Info1:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info2:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info3:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info4:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info5:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info6:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info7:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info11:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info12:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info13:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info14:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info15:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info16:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info19:
                  description: Additional requester-provided metadata field
                  type: string
                RvrslOptn:
                  type: string
                Tmstmp:
                  type: string
              type: object
          type: object
      type: object
    GetAccountTransactionsListResponse:
      properties:
        data:
          $ref: '#/components/schemas/GetAccountTransactionsListResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    GetAccountTransactionsListResponseData:
      description: Response data payload - customize per operation
      type: object
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
        - $ref: '#/components/schemas/RequestHeader'
        - properties:
            code:
              description: Response code
              type: string
            info:
              description: Response message
              type: string
          type: object
      type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: Get Account Transactions List
  version: 1.0.0
  x-ibm-name: get-account-transactions-list
openapi: 3.0.0
paths:
  /get-account-transactions-list:
    post:
      operationId: GetAccountTransactionsList
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAccountTransactionsListRequest'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountTransactionsListResponse'
          description: success
security:
  - clientID: []
    clientSecret: []
  - oAuth:
      - Integration_scope
servers:
  - url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
      - operation-switch:
          case:
            - execute:
                - invoke:
                    backend-type: json
                    chunked-uploads: true
                    follow-redirects: false
                    header-control:
                      type: blocklist
                      values: []
                    inject-proxy-headers: true
                    parameter-control:
                      type: allowlist
                      values: []
                    persistent-connection: true
                    target-url: $(target-url)
                    timeout: 60
                    title: invoke
                    verb: POST
                    version: 2.0.0
              operations:
                - GetAccountTransactionsList
          otherwise: []
          title: operation-switch
          version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://get-account-transaction-list-http-bab-sit-cp4i.apps.babsitaro.albtests.com/GetAccountTransactionList
  testable: true
  type: rest
