components:
  schemas:
    ManageRegisteredBillsRequest:
            type: object
            properties:
              EAIMessage:
                type: object
                description: Enterprise Application Integration envelope containing header metadata and business payload
                properties:
                  Body:
                    type: object
                    description: Business request payload specific to the service operation
                    properties:
                      Actn:
                        type: string
                      Addrss_Dtls:
                        type: object
                        properties:
                          Cntry:
                            type: string
                          Cty:
                            type: string
                          Dstrct:
                            type: string
                          Email:
                            type: string
                          Fax_No:
                            type: string
                          Mail_Tp:
                            type: string
                          Mbl_No:
                            type: string
                          Phn_No:
                            type: string
                          Rsdnc_Bldng_No:
                            type: string
                          Rsdnc_Cty:
                            type: string
                          Rsdnc_Dstrct:
                            type: string
                          Rsdnc_Strt:
                            type: string
                          Strt:
                            type: string
                          Wrk_Fax:
                            type: string
                          Wrk_Phn_No:
                            type: string
                          Wsl_Adtnl_Cd:
                            type: string
                          Wsl_Bldng_No:
                            type: string
                          Wsl_Unit_No:
                            type: string
                          Wsl_Zip_Cd:
                            type: string
                        additionalProperties: false
                      Addtnl_Info:
                        type: object
                        properties:
                          Auth_Dt:
                            type: string
                          Auth_Md:
                            type: string
                          Incmng_Frgn_Trnsfr_Amt:
                            type: string
                          Outgng_Frgn_Trnsfr_Amt:
                            type: string
                          Prcd_Cust_Acct_Opn_Flg:
                            type: string
                        additionalProperties: false
                      Athrztn_Actn:
                        type: string
                      Auth_Key:
                        type: string
                      Bsc_Info:
                        type: object
                        properties:
                          DOB_G:
                            type: string
                          DOB_H:
                            type: string
                          Edctn_Lvl:
                            type: string
                          Gndr:
                            type: string
                          Nm_1_Ar:
                            type: string
                          Nm_1_En:
                            type: string
                          Nm_2_Ar:
                            type: string
                          Nm_2_En:
                            type: string
                          Nm_3_Ar:
                            type: string
                          Nm_3_En:
                            type: string
                          Nm_4_Ar:
                            type: string
                          Nm_4_En:
                            type: string
                          Ntnlty:
                            type: string
                          POB_CTY:
                            type: string
                          Prfrrd_Lang:
                            type: string
                          Ttl:
                            type: string
                        additionalProperties: false
                      Digi_KYC_Elgblty_Flg:
                        type: string
                      Digi_KYC_Elgblty_Rsn:
                        type: string
                      Dsclmr_Lst:
                        type: object
                        properties:
                          Dsclmr_Dtls:
                            type: object
                            properties:
                              Dsclmr_Cnfrmd:
                                type: string
                              Dsclmr_Cnfrmd_Chnl:
                                type: string
                              Dsclmr_Cnfrmd_Dt:
                                type: string
                              Dsclmr_Tp:
                                type: string
                            additionalProperties: false
                        additionalProperties: false
                      Email:
                        type: string
                      Emplyr_Dtls:
                        type: object
                        properties:
                          Pstn:
                            type: string
                          Sctr:
                            type: string
                        additionalProperties: false
                      Exctn_Md:
                        type: string
                      Grdn_Info:
                        type: object
                        properties:
                          DOB_G:
                            type: string
                          DOB_H:
                            type: string
                          Rsdnc_Addrss:
                            type: string
                        additionalProperties: false
                      Gurd_NIN:
                        type: string
                      Hm_Cntry_Dtls:
                        type: string
                      IAM_Updt_Dt:
                        type: string
                      ID_Expry_Dt_H:
                        type: string
                      ID_Lst:
                        type: object
                        properties:
                          ID_Dtls:
                            type: object
                            properties:
                              ID_Expry_Dt_H:
                                type: string
                              ID_Iss_Plc:
                                type: string
                              ID_No:
                                type: string
                              ID_Tp:
                                type: string
                            additionalProperties: false
                        additionalProperties: false
                      ID_Tp:
                        type: string
                      Mbl_No:
                        type: string
                      Mnthly_Incm:
                        type: string
                      Mobl_No:
                        type: string
                      NIN:
                        type: string
                      Ntnlty:
                        type: string
                      Reg_Chnl_Id:
                        type: string
                      Reg_Date:
                        type: string
                      Rqstr_Info2:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info7:
                        type: string
                        description: Additional requester-provided metadata field
                      Sgmnt:
                        type: string
                      Tmstmp:
                        type: string
                      VIP_Flg:
                        type: string
                      Vrfd_Mbl_No:
                        type: string
                      Vsa_Dtls:
                        type: object
                        properties:
                          Expctd_Arvl_Dt:
                            type: string
                          Vsa_No:
                            type: string
                        additionalProperties: false
                      channelId:
                        type: string
                        description: Channel from which the request originated
                      lang:
                        type: string
                      messageFormat:
                        type: string
                        description: Message payload format (JSON or XML)
                      outputType:
                        type: string
                    additionalProperties: false
                  EAIHeader:
                    type: object
                    description: Technical and routing metadata required for request processing and tracking
                    properties:
                      BE_Ref_No:
                        type: string
                      CIF:
                        type: string
                      ChnlId:
                        type: string
                      EAIRtrnCd:
                        type: string
                      EAIRtrnCdDesc:
                        type: string
                      FE_Ref_No:
                        type: string
                      FunctnId:
                        type: string
                      Lang:
                        type: string
                      MsgFrmt:
                        type: string
                      OrgnlMsgId:
                        type: string
                      Orgnl_Data_Val:
                        type: string
                      Rqstr_Info1:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info11:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info12:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info13:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info14:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info15:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info16:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info19:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info2:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info3:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info4:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info5:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info6:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info7:
                        type: string
                        description: Additional requester-provided metadata field
                      RvrslOptn:
                        type: string
                      Sgmnt:
                        type: string
                      TmStmp:
                        type: string
                      Trx_Md:
                        type: string
                      UsrDfn:
                        type: string
                    additionalProperties: false
                additionalProperties: false
            additionalProperties: false
    ManageRegisteredBillsResponse:
      properties:
        data:
          $ref: '#/components/schemas/ManageRegisteredBillsResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    ManageRegisteredBillsResponseData:
      description: Response data payload - customize per operation
      type: object
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            description: Response code
            type: string
          info:
            description: Response message
            type: string
        type: object
      type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: Manage Registered Bills
  version: 1.0.0
  x-ibm-name: manage-registered-bills
openapi: 3.0.0
paths:
  /manage-registered-bills:
    post:
      operationId: ManageRegisteredBills
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManageRegisteredBillsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManageRegisteredBillsResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - ManageRegisteredBills
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://manage-registered-bills-http-bab-sit-cp4i.apps.babsitaro.albtests.com/ManageRegisteredBills
  testable: true
  type: rest
