components:
  schemas:
    ManageCustomerAccountRequestRequest:
            type: object
            properties:
              EAIMessage:
                type: object
                description: Enterprise Application Integration envelope containing header metadata and business payload
                properties:
                  Body:
                    type: object
                    description: Business request payload specific to the service operation
                    properties:
                      Acct_Ctgry:
                        type: string
                      Acct_Nick_Name:
                        type: string
                      Acct_No:
                        type: string
                      Acct_Sub_Tp:
                        type: string
                      Acct_Tp:
                        type: string
                      Acct_Ttl:
                        type: string
                      Cntrct_Prd:
                        type: string
                      Crd_Prdct_Cd:
                        type: string
                      Exctn_Md:
                        type: string
                      Fees_Acct_No:
                        type: string
                      Intl_Dpst_Amt:
                        type: string
                      Kd_ID_No:
                        type: string
                      Lnkd_Acct_No:
                        type: string
                      Mtrty_Crdt_Instrctn:
                        type: string
                      Stmt_Dlvry_Mthd:
                        type: string
                      Stmt_Frqncy:
                        type: string
                      Tmstmp:
                        type: string
                      lang:
                        type: string
                    additionalProperties: false
                  EAIHeader:
                    type: object
                    description: Technical and routing metadata required for request processing and tracking
                    properties:
                      BE_Ref_No:
                        type: string
                      CIF:
                        type: string
                      ChnlId:
                        type: string
                      EAIRtrnCd:
                        type: string
                      FE_Ref_No:
                        type: string
                      FunctnId:
                        type: string
                      Lang:
                        type: string
                      MsgFrmt:
                        type: string
                      OrgnlMsgId:
                        type: string
                      Rqstr_Info1:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info11:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info12:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info13:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info14:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info15:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info16:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info19:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info2:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info3:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info4:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info5:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info6:
                        type: string
                        description: Additional requester-provided metadata field
                      Rqstr_Info7:
                        type: string
                        description: Additional requester-provided metadata field
                      RvrslOptn:
                        type: string
                      Sgmnt:
                        type: string
                      Tmstmp:
                        type: string
                    additionalProperties: false
                additionalProperties: false
            additionalProperties: false
    ManageCustomerAccountRequestRequestData:
      type: object
    ManageCustomerAccountRequestResponse:
      properties:
        data:
          $ref: '#/components/schemas/ManageCustomerAccountRequestResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    ManageCustomerAccountRequestResponseData:
      type: object
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            type: string
          info:
            type: string
        type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: Manage Customer Account Request
  version: 1.0.0
  x-ibm-name: manage-customer-account-request
openapi: 3.0.0
paths:
  /manage-customer-account-request:
    post:
      operationId: ManageCustomerAccountRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManageCustomerAccountRequestRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManageCustomerAccountRequestResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - ManageCustomerAccountRequest
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://manage-customer-account-http-bab-sit-cp4i.apps.babsitaro.albtests.com/ManageCustomerAccountRequest
  testable: true
  type: rest
