openapi: 3.0.0
info:
  version: 1.0.0
  title: Mubasher Cash Withdrawal
  x-ibm-name: mubasher-cash-withdrawal
servers:
  - url: /albilad-api/v1
x-ibm-configuration:
  properties:
    target-url:
      value: >-
        http://mubasher-cash-withdrawal-http-bab-sit-cp4i.apps.babsitaro.albtests.com/MubasherCashWithdrawal
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: false
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - operation-switch:
          version: 2.0.0
          title: operation-switch
          case:
            - operations:
                - MubasherCashWithdrawal
              execute:
                - invoke:
                    version: 2.0.0
                    title: invoke
                    backend-type: json
                    header-control:
                      type: blocklist
                      values: []
                    parameter-control:
                      type: allowlist
                      values: []
                    timeout: 60
                    verb: POST
                    chunked-uploads: true
                    persistent-connection: true
                    target-url: $(target-url)
                    follow-redirects: false
                    inject-proxy-headers: true
          otherwise: []
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /mubasher-cash-withdrawal:
    post:
      operationId: MubasherCashWithdrawal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MubasherCashWithdrawalRequest'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MubasherCashWithdrawalResponse'
components:
  securitySchemes:
    clientID:
      type: apiKey
      in: header
      name: X-IBM-Client-Id
      x-key-type: client_id
    clientSecret:
      type: apiKey
      in: header
      name: X-IBM-Client-Secret
      x-key-type: client_secret
    oAuth:
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
      flows:
        clientCredentials:
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
          scopes:
            Integration_scope: Integration_scope
  schemas:
    MubasherCashWithdrawalRequest:
      {
          "type": "object",
          "properties": {
              "header": {
                  "type": "object",
                  "properties": {
                      "messageFormat": {
                          "type": "string"
                      },
                      "cif": {
                          "type": "string"
                      },
                      "channelId": {
                          "type": "string"
                      },
                      "functionId": {
                          "type": "string"
                      },
                      "language": {
                          "type": "string"
                      },
                      "reversalOption": {
                          "type": "string"
                      },
                      "segment": {
                          "type": "string"
                      },
                      "requesterInfo1": {
                          "type": "string"
                      },
                      "requesterInfo2": {
                          "type": "string"
                      },
                      "deviceInfo": {
                          "type": "object",
                          "properties": {
                              "model": {
                                  "type": "string"
                              },
                              "osType": {
                                  "type": "string"
                              },
                              "osVersion": {
                                  "type": "string"
                              },
                              "id": {
                                  "type": "string"
                              },
                              "ipAddress": {
                                  "type": "string"
                              },
                              "city": {
                                  "type": "string"
                              },
                              "country": {
                                  "type": "string"
                              }
                          }
                      },
                      "frontendReferenceNumber": {
                          "type": "string"
                      },
                      "backendReferenceNumber": {
                          "type": "string"
                      },
                      "transactionDateTime": {
                          "type": "string"
                      }
                  }
              },
              "body": {
                  "type": "object",
                  "properties": {
                      "amount": {
                          "type": "number"
                      },
                      "accountId": {
                          "type": "string"
                      }
                  }
              }
          }
      }    RequestHeader:
      type: object
      properties:
        messageFormat:
          type: string
        cif:
          type: string
        channelId:
          type: string
        functionId:
          type: string
        language:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        deviceInfo:
          type: object
          properties:
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            city:
              type: string
            country:
              type: string
        frontendReferenceNumber:
          type: string
        backendReferenceNumber:
          type: string
        transactionDateTime:
          type: string

    MubasherCashWithdrawalResponse:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/ResponseHeader'
        data:
          $ref: '#/components/schemas/MubasherCashWithdrawalResponseData'
    ResponseHeader:
      allOf:
        - $ref: '#/components/schemas/RequestHeader'
        - type: object
          properties:
            code:
              type: string
            info:
              type: string
    MubasherCashWithdrawalResponseData:
      type: object
    
security:
  - clientID: []
    clientSecret: []
  - oAuth:
      - Integration_scope
