components:
  schemas:
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    RequestStatementRequest:
            type: object
            properties:
              data:
                type: object
                properties:
                  actn:
                    type: string
                  cmsAcctNumber:
                    type: string
                  dlvryMthd:
                    type: string
                  endDt:
                    type: string
                  lglId:
                    type: string
                  strtDt:
                    type: string
                  sttmntLng:
                    type: string
                  sttmntTp:
                    type: string
                  stts:
                    type: string
                additionalProperties: false
              header:
                type: object
                properties:
                  backendReferenceNumber:
                    type: string
                    description: Backend system reference number
                  channelId:
                    type: string
                    description: Channel from which the request originated
                  cif:
                    type: string
                    description: Customer Information File number
                  deviceInfo:
                    type: object
                    properties:
                      city:
                        type: string
                      country:
                        type: string
                      id:
                        type: string
                      ipAddress:
                        type: string
                      model:
                        type: string
                      osVersion:
                        type: string
                    additionalProperties: false
                  eaiReturnCode:
                    type: string
                  frontendReferenceNumber:
                    type: string
                    description: Frontend system reference number
                  functionId:
                    type: string
                    description: Identifier of the business function being invoked
                  language:
                    type: string
                    description: Request language code
                  messageFormat:
                    type: string
                    description: Message payload format (JSON or XML)
                  originalMessageId:
                    type: string
                  requesterInformation1:
                    type: string
                  requesterInformation14:
                    type: string
                  requesterInformation19:
                    type: string
                  requesterInformation2:
                    type: string
                  requesterInformation3:
                    type: string
                  requesterInformation5:
                    type: string
                  requesterInformation6:
                    type: string
                  requesterInformation7:
                    type: string
                  reversalOption:
                    type: string
                    description: Indicates whether the transaction can be reversed
                  timeStamp:
                    type: string
                additionalProperties: false
            additionalProperties: false
    RequestStatementResponse:
      properties:
        data:
          $ref: '#/components/schemas/RequestStatementResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    RequestStatementResponseData:
      description: Response data payload - customize per operation
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            description: Response code
            type: string
          info:
            description: Response message
            type: string
        type: object
      type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: Request Statement
  version: 1.0.0
  x-ibm-name: request-statement
openapi: 3.0.0
paths:
  /request-statement:
    post:
      operationId: RequestStatement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestStatementRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestStatementResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - RequestStatement
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://request-statement-http-bab-sit-cp4i.apps.babsitaro.albtests.com/requeststatement
  testable: true
  type: rest
