components:
  schemas:
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
        - $ref: '#/components/schemas/RequestHeader'
        - properties:
            code:
              description: Response code
              type: string
            info:
              description: Response message
              type: string
          type: object
      type: object
    TanfeethInquiryFISalaryInqResponse:
      properties:
        data:
          $ref: '#/components/schemas/TanfeethInquiryFISalaryInqResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    TanfeethInquiryFISalaryInqResponseData:
      description: Response data payload - customize per operation
      type: object
    TanfeethInquiryFISalaryInqRequest:
      type: object
      properties: {}
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: Tanfeeth Inquiry FISalaryInq
  version: 1.0.0
  x-ibm-name: tanfeeth-inquiry-fisalaryinq
openapi: 3.0.0
paths:
  /tanfeeth-inquiry-fisalaryinq:
    post:
      operationId: TanfeethInquiryFISalaryInq
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TanfeethInquiryFISalaryInqRequest'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TanfeethInquiryFISalaryInqResponse'
          description: success
security:
  - clientID: []
    clientSecret: []
  - oAuth:
      - Integration_scope
servers:
  - url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
      - operation-switch:
          case:
            - execute:
                - invoke:
                    backend-type: json
                    chunked-uploads: true
                    follow-redirects: false
                    header-control:
                      type: blocklist
                      values: []
                    inject-proxy-headers: true
                    parameter-control:
                      type: allowlist
                      values: []
                    persistent-connection: true
                    target-url: $(target-url)
                    timeout: 60
                    title: invoke
                    verb: POST
                    version: 2.0.0
              operations:
                - TanfeethInquiryFISalaryInq
          otherwise: []
          title: operation-switch
          version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://tanfeeth-inquiry-http-bab-sit-cp4i.apps.babsitaro.albtests.com/bea/ws/gi/fi/salaryinq/v01
  testable: true
  type: rest
