components:
  schemas:
    AuthenticateUserRequest:
      additionalProperties: false
      properties:
        EAIMessage:
          additionalProperties: false
          description: Enterprise Application Integration envelope containing header
            metadata and business payload
          properties:
            Body:
              additionalProperties: false
              description: Business request payload specific to the service operation
              properties:
                Auth_Prps:
                  type: string
                Clndr:
                  type: string
                Cust_DOB:
                  type: string
                ID_No:
                  type: string
                Mbl_No:
                  type: string
                Rqstr_Info7:
                  description: Additional requester-provided metadata field
                  type: string
                Tmstmp:
                  type: string
                outputType:
                  type: string
              type: object
            EAIHeader:
              additionalProperties: false
              description: Technical and routing metadata required for request processing
                and tracking
              properties:
                BE_Ref_No:
                  type: string
                CIF:
                  type: string
                ChnlId:
                  type: string
                EAIRtrnCd:
                  type: string
                FE_Ref_No:
                  type: string
                FunctnId:
                  type: string
                Lang:
                  type: string
                MsgFrmt:
                  type: string
                OrgnlMsgId:
                  type: string
                Rqstr_Info1:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info2:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info3:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info4:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info5:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info6:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info7:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info11:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info12:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info13:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info14:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info15:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info16:
                  description: Additional requester-provided metadata field
                  type: string
                RvrslOptn:
                  type: string
                Tmstmp:
                  type: string
              type: object
          type: object
      type: object
    AuthenticateUserRequestData:
      properties:
        amount:
          type: string
        chargeTypeId:
          type: string
        cmsReplacementNumber:
          type: string
        creditAccount:
          type: string
        debitAccount:
          type: string
        subFunctionId:
          type: string
        t24Application:
          type: string
        userDefined1:
          type: string
        userDefined2:
          type: string
        userDefined3:
          type: string
        userDefined4:
          type: string
      type: object
    AuthenticateUserResponse:
      properties:
        data:
          $ref: '#/components/schemas/AuthenticateUserResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    AuthenticateUserResponseData:
      properties:
        chargeAmount:
          type: string
        chargeTotalAmount:
          type: string
        chargeVatAmount:
          type: string
        chargeVatPercentage:
          type: string
        userDefined1:
          type: string
        userDefined2:
          type: string
      type: object
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            type: string
          info:
            type: string
        type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: Authenticate User
  version: 1.0.0
  x-ibm-name: authenticate-user
openapi: 3.0.0
paths:
  /authenticate-user:
    post:
      operationId: AuthenticateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticateUserRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticateUserResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - AuthenticateUser
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://authenticate-user-http-bab-sit-cp4i.apps.babsitaro.albtests.com/authenticate/user
  testable: true
  type: rest
