openapi: 3.0.0
info:
  version: 1.0.0
  title: Authenticate User Mock - Authenticate
  x-ibm-name: authenticate-user-mock---authenticate
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  properties:
    target-url:
      value: http://authenticate-user-http-bab-sit-cp4i.apps.babsitaro.albtests.com/bib-ldap/authenticate
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: false
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - operation-switch:
        version: 2.0.0
        title: operation-switch
        case:
        - operations:
          - AuthenticateUserMock-Authenticate
          execute:
          - invoke:
              version: 2.0.0
              title: invoke
              backend-type: json
              header-control:
                type: blocklist
                values: []
              parameter-control:
                type: allowlist
                values: []
              timeout: 60
              verb: POST
              chunked-uploads: true
              persistent-connection: true
              target-url: $(target-url)
              follow-redirects: false
              inject-proxy-headers: true
        otherwise: []
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /authenticate-user-mock---authenticate:
    post:
      operationId: AuthenticateUserMock-Authenticate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticateUserMock-AuthenticateRequest'
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticateUserMock-AuthenticateResponse'
components:
  securitySchemes:
    clientID:
      type: apiKey
      in: header
      name: X-IBM-Client-Id
      x-key-type: client_id
    clientSecret:
      type: apiKey
      in: header
      name: X-IBM-Client-Secret
      x-key-type: client_secret
    oAuth:
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
      flows:
        clientCredentials:
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
          scopes:
            Integration_scope: Integration_scope
  schemas:
    AuthenticateUserMock-AuthenticateRequest:
      type: object
      properties:
        EAIMessage:
          type: object
          description: Enterprise Application Integration envelope containing header
            metadata and business payload
          properties:
            Body:
              type: object
              description: Business request payload specific to the service operation
              properties:
                Auth_Prps:
                  type: string
                Clndr:
                  type: string
                Cust_DOB:
                  type: string
                ID_No:
                  type: string
                Mbl_No:
                  type: string
                OrgnlMsgId:
                  type: string
                outputType:
                  type: string
              additionalProperties: false
            EAIHeader:
              type: object
              description: Technical and routing metadata required for request processing
                and tracking
              properties:
                BE_Ref_No:
                  type: string
                  description: Backend system reference number
                CIF:
                  type: string
                  description: Customer Information File number
                ChnlId:
                  type: string
                  description: Channel from which the request originated
                EAIRtrnCd:
                  type: string
                FE_Ref_No:
                  type: string
                  description: Frontend system reference number
                FunctnId:
                  type: string
                  description: Identifier of the business function being invoked
                Lang:
                  type: string
                  description: Request language code
                MsgFrmt:
                  type: string
                  description: Message payload format (JSON or XML)
                Rqstr_Info1:
                  type: string
                  description: Additional requester-provided metadata field
                Rqstr_Info11:
                  type: string
                  description: Additional requester-provided metadata field
                Rqstr_Info12:
                  type: string
                  description: Additional requester-provided metadata field
                Rqstr_Info13:
                  type: string
                  description: Additional requester-provided metadata field
                Rqstr_Info14:
                  type: string
                  description: Additional requester-provided metadata field
                Rqstr_Info15:
                  type: string
                  description: Additional requester-provided metadata field
                Rqstr_Info16:
                  type: string
                  description: Additional requester-provided metadata field
                Rqstr_Info2:
                  type: string
                  description: Additional requester-provided metadata field
                Rqstr_Info3:
                  type: string
                  description: Additional requester-provided metadata field
                Rqstr_Info4:
                  type: string
                  description: Additional requester-provided metadata field
                Rqstr_Info5:
                  type: string
                  description: Additional requester-provided metadata field
                Rqstr_Info6:
                  type: string
                  description: Additional requester-provided metadata field
                Rqstr_Info7:
                  type: string
                  description: Additional requester-provided metadata field
                RvrslOptn:
                  type: string
                  description: Indicates whether the transaction can be reversed
                Tmstmp:
                  type: string
                  description: Request timestamp in ISO 8601 format
              additionalProperties: false
          additionalProperties: false
      additionalProperties: false
    AuthenticateUserMock-AuthenticateResponse:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/ResponseHeader'
        data:
          $ref: '#/components/schemas/AuthenticateUserMock-AuthenticateResponseData'
    RequestHeader:
      type: object
      properties:
        messageFormat:
          type: string
        cif:
          type: string
        channelId:
          type: string
        functionId:
          type: string
        language:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        deviceInfo:
          type: object
          properties:
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            city:
              type: string
            country:
              type: string
        frontendReferenceNumber:
          type: string
        backendReferenceNumber:
          type: string
        transactionDateTime:
          type: string
    ResponseHeader:
      type: object
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - type: object
        properties:
          code:
            type: string
            description: Response code
          info:
            type: string
            description: Response message
    AuthenticateUserMock-AuthenticateResponseData:
      type: object
      description: Response data payload - customize per operation
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
