components:
  schemas:
    Demo2ServiceRequest:
      additionalProperties: false
      description: Demo Service Request - Complete request structure with EAIHeader
        and body
      properties:
        EAIMessage:
          additionalProperties: false
          properties:
            Body:
              additionalProperties: false
              description: Request body with business-specific data
              properties:
                accountNumber:
                  description: The account number
                  example: 1234567890
                  maxLength: 20
                  minLength: 10
                  pattern: ^[0-9]+$
                  type: string
                amount:
                  description: Transaction amount with decimal precision
                  example: 1000.5
                  exclusiveMinimum: false
                  format: double
                  minimum: 0
                  type: number
                currency:
                  default: SAR
                  description: ISO 4217 currency code
                  example: SAR
                  maxLength: 3
                  minLength: 3
                  pattern: ^[A-Z]{3}$
                  type: string
                customerId:
                  description: Unique customer identifier
                  example: CUST-001
                  type: string
                metadata:
                  additionalProperties: false
                  description: Additional transaction metadata
                  properties:
                    notes:
                      description: Additional notes
                      example: Customer initiated transaction
                      maxLength: 500
                      type: string
                    source:
                      description: Source of the transaction
                      example: mobile_app
                      type: string
                  type: object
                transactionType:
                  description: Type of transaction
                  enum:
                  - DEPOSIT
                  - WITHDRAWAL
                  - TRANSFER
                  - INQUIRY
                  example: INQUIRY
                  type: string
              required:
              - accountNumber
              - customerId
              type: object
            EAIHeader:
              additionalProperties: false
              properties:
                backendReferenceNumber:
                  description: Backend system reference number
                  example: BE987654321
                  type: string
                channelId:
                  description: Channel identifier
                  enum:
                  - MOB
                  - WEB
                  - ATM
                  - BRANCH
                  example: MOB
                  type: string
                cif:
                  description: Customer Information File number
                  example: 1234567
                  type: string
                deviceInfo:
                  additionalProperties: false
                  description: Device information for the request
                  properties:
                    city:
                      description: City of the device location
                      example: Riyadh
                      type: string
                    country:
                      description: ISO 3166-1 alpha-2 country code
                      example: SA
                      maxLength: 2
                      minLength: 2
                      type: string
                    id:
                      description: Unique device identifier
                      example: ABC123XYZ
                      type: string
                    ipAddress:
                      description: Device IP address
                      example: 192.168.1.100
                      format: ipv4
                      type: string
                    model:
                      description: Device model
                      example: iPhone 14
                      type: string
                    osType:
                      description: Operating system type
                      example: iOS
                      type: string
                    osVersion:
                      description: Operating system version
                      example: 16.5
                      type: string
                  type: object
                frontendReferenceNumber:
                  description: Frontend system reference number
                  example: FE123456789
                  type: string
                functionId:
                  description: Function identifier
                  example: DEMO_FUNC_001
                  type: string
                language:
                  description: Language code
                  enum:
                  - EN
                  - AR
                  example: EN
                  type: string
                messageFormat:
                  description: Message format type
                  enum:
                  - JSON
                  - XML
                  example: JSON
                  type: string
                requesterInfo1:
                  description: Additional requester information field 1
                  type: string
                requesterInfo2:
                  description: Additional requester information field 2
                  type: string
                reversalOption:
                  description: Indicates if transaction can be reversed
                  example: false
                  type: boolean
                segment:
                  description: Customer segment
                  example: RETAIL
                  type: string
                transactionDateTime:
                  description: Transaction timestamp in ISO 8601 format
                  example: "2024-12-14T10:30:00Z"
                  format: date-time
                  type: string
              required:
              - channelId
              - functionId
              - transactionDateTime
              type: object
          required:
          - EAIHeader
          - Body
          type: object
      required:
      - EAIMessage
      type: object
    Demo2ServiceResponse:
      properties:
        data:
          $ref: '#/components/schemas/Demo2ServiceResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    Demo2ServiceResponseData:
      description: Response data payload - customize per operation
      type: object
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            description: Response code
            type: string
          info:
            description: Response message
            type: string
        type: object
      type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: Demo2 Service
  version: 1.0.0
  x-ibm-name: demo2-service
openapi: 3.0.0
paths:
  /demo2-service:
    post:
      operationId: Demo2Service
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Demo2ServiceRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Demo2ServiceResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - Demo2Service
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://esb.example.com/demo1
  testable: true
  type: rest
