components:
  schemas:
    ManageOutboundRequest:
      additionalProperties: false
      properties:
        data:
          additionalProperties: false
          properties:
            lng:
              type: string
            mobile:
              type: string
            srvcTp:
              type: string
          type: object
        header:
          additionalProperties: false
          properties:
            channelId:
              description: Channel from which the request originated
              type: string
            cif:
              description: Customer Information File number
              type: string
            frontendReferenceNumber:
              description: Frontend system reference number
              type: string
            functionId:
              description: Identifier of the business function being invoked
              type: string
            language:
              description: Request language code
              type: string
            msgFormat:
              type: string
            reversalOption:
              description: Indicates whether the transaction can be reversed
              type: string
          type: object
      type: object
    ManageOutboundResponse:
      properties:
        data:
          $ref: '#/components/schemas/ManageOutboundResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    ManageOutboundResponseData:
      description: Response data payload - customize per operation
      type: object
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            description: Response code
            type: string
          info:
            description: Response message
            type: string
        type: object
      type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: Manage Outbound
  version: 1.0.0
  x-ibm-name: manage-outbound
openapi: 3.0.0
paths:
  /manage-outbound:
    post:
      operationId: ManageOutbound
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManageOutboundRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManageOutboundResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - ManageOutbound
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://manage-outbound-http-bab-sit-cp4i.apps.babsitaro.albtests.com/manageoutbound
  testable: true
  type: rest
