components:
  schemas:
    MubasherCashWithdrawalRequest:
      additionalProperties: false
      properties:
        MsgRoot:
          additionalProperties: false
          properties:
            Header:
              additionalProperties: false
              properties:
                FragmentID:
                  type: string
                IsLast:
                  type: string
                ReturnCode:
                  type: string
                TimeStamp:
                  type: string
              type: object
            TransactionData:
              additionalProperties: false
              properties:
                BeneficiaryAccount:
                  type: string
                BeneficiaryBIC:
                  type: string
                CreditAmount:
                  type: string
                CreditCurrency:
                  type: string
                CreditValueDate:
                  type: string
                DebitAmount:
                  type: string
                DebitCurrency:
                  type: string
                DebitValueDate:
                  type: string
                Narration:
                  type: string
                OmnibusAccountID:
                  type: string
                OmnibusBIC:
                  type: string
                OmnibusCustomerDetails:
                  type: string
                TransactionID:
                  type: string
                TxnType:
                  type: string
                VirtualAccNo:
                  type: string
              type: object
          type: object
      type: object
    MubasherCashWithdrawalRequestData:
      type: object
    MubasherCashWithdrawalResponse:
      properties:
        data:
          $ref: '#/components/schemas/MubasherCashWithdrawalResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    MubasherCashWithdrawalResponseData:
      type: object
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            type: string
          info:
            type: string
        type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: Mubasher Cash Withdrawal
  version: 1.0.0
  x-ibm-name: mubasher-cash-withdrawal
openapi: 3.0.0
paths:
  /mubasher-cash-withdrawal:
    post:
      operationId: MubasherCashWithdrawal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MubasherCashWithdrawalRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MubasherCashWithdrawalResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - MubasherCashWithdrawal
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://mubasher-cash-withdrawal-http-bab-sit-cp4i.apps.babsitaro.albtests.com/MubasherCashWithdrawal
  testable: true
  type: rest
