components:
  schemas:
    MubasherCashDepositRequest:
      additionalProperties: false
      properties:
        EAIMessage:
          additionalProperties: false
          description: Enterprise Application Integration envelope containing header
            metadata and business payload
          properties:
            Body:
              additionalProperties: false
              description: Business request payload specific to the service operation
              properties:
                CR_Amt:
                  type: string
                CR_Cry:
                  type: string
                CR_Vlu_Dt:
                  type: string
                DR_Amt:
                  type: string
                DR_Cry:
                  type: string
                DR_Vlu_Dt:
                  type: string
                Dpst_Tp:
                  type: string
                MF_Acct_No:
                  type: string
                MF_Name_Ar:
                  type: string
                MF_Name_En:
                  type: string
                Omni_Bus_Acct_Id:
                  type: string
                Trx_Desc_Ar:
                  type: string
                Trx_Desc_En:
                  type: string
                Vrtul_Acct_No:
                  type: string
              type: object
            EAIHeader:
              additionalProperties: false
              description: Technical and routing metadata required for request processing
                and tracking
              properties:
                BE_Ref_No:
                  type: string
                CIF:
                  type: string
                ChnlId:
                  type: string
                EAIRtrnCd:
                  type: string
                FE_Ref_No:
                  type: string
                FunctnId:
                  type: string
                Lang:
                  type: string
                Mrchnt_Ctgry_Cd:
                  type: string
                MsgFrmt:
                  type: string
                Orgnl_Data_Val:
                  type: string
                OrgnlMsgId:
                  type: string
                Ovrrd_Clss:
                  type: string
                Rqstr_Info1:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info2:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info3:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info4:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info5:
                  description: Additional requester-provided metadata field
                  type: string
                RvrslOptn:
                  type: string
                Tmstmp:
                  type: string
                Trx_Md:
                  type: string
                UsrDfn:
                  type: string
              type: object
          type: object
      type: object
    MubasherCashDepositResponse:
      properties:
        data:
          $ref: '#/components/schemas/MubasherCashDepositResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    MubasherCashDepositResponseData:
      description: Response data payload - customize per operation
      type: object
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            description: Response code
            type: string
          info:
            description: Response message
            type: string
        type: object
      type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: Mubasher Cash Deposit
  version: 1.0.0
  x-ibm-name: mubasher-cash-deposit
openapi: 3.0.0
paths:
  /mubasher-cash-deposit:
    post:
      operationId: MubasherCashDeposit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MubasherCashDepositRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MubasherCashDepositResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - MubasherCashDeposit
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://mubasher-cash-deposit-http-bab-sit-cp4i.apps.babsitaro.albtests.com/MubasherCashDeposit
  testable: true
  type: rest
