components:
  schemas:
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            description: Response code
            type: string
          info:
            description: Response message
            type: string
        type: object
      type: object
    SADADReconciliationRequest:
      additionalProperties: false
      properties:
        EAIMessage:
          additionalProperties: false
          description: Enterprise Application Integration envelope containing header
            metadata and business payload
          properties:
            Body:
              additionalProperties: false
              description: Business request payload specific to the service operation
              properties:
                BankCutOffRq:
                  additionalProperties: false
                  properties:
                    FilePathName:
                      type: string
                    PrcDt:
                      type: string
                  type: object
                BankReconDownloadRq:
                  additionalProperties: false
                  properties:
                    FilePathName:
                      type: string
                    PrcDt:
                      type: string
                  type: object
                BankReconRefundDownloadRq:
                  additionalProperties: false
                  properties:
                    FilePathName:
                      type: string
                    PrcDt:
                      type: string
                  type: object
                BankRefundCutOffRq:
                  additionalProperties: false
                  properties:
                    FilePathName:
                      type: string
                    PrcDt:
                      type: string
                  type: object
                BankSplUploadRq:
                  additionalProperties: false
                  properties:
                    FilePathName:
                      type: string
                    PrcDt:
                      type: string
                  type: object
                BankSrlUploadRq:
                  additionalProperties: false
                  properties:
                    FilePathName:
                      type: string
                    PrcDt:
                      type: string
                  type: object
                OrgnlMsgId:
                  type: string
                Ovrrd_Clss:
                  type: string
                Status:
                  additionalProperties: false
                  properties:
                    Severity:
                      type: string
                    ShortDesc:
                      type: string
                    StatusCode:
                      type: string
                  type: object
              type: object
            EAIHeader:
              additionalProperties: false
              description: Technical and routing metadata required for request processing
                and tracking
              properties:
                BE_Ref_No:
                  description: Backend system reference number
                  type: string
                CIF:
                  description: Customer Information File number
                  type: string
                ChnlId:
                  description: Channel from which the request originated
                  type: string
                EAIRtrnCd:
                  type: string
                FE_Ref_No:
                  description: Frontend system reference number
                  type: string
                FunctnId:
                  description: Identifier of the business function being invoked
                  type: string
                Lang:
                  description: Request language code
                  type: string
                MsgFrmt:
                  description: Message payload format (JSON or XML)
                  type: string
                Rqstr_Info1:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info2:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info3:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info4:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info5:
                  description: Additional requester-provided metadata field
                  type: string
                RvrslOptn:
                  description: Indicates whether the transaction can be reversed
                  type: string
                Tmstmp:
                  description: Request timestamp in ISO 8601 format
                  type: string
                UsrDfn:
                  type: string
              type: object
          type: object
      type: object
    SADADReconciliationResponse:
      properties:
        data:
          $ref: '#/components/schemas/SADADReconciliationResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    SADADReconciliationResponseData:
      description: Response data payload - customize per operation
      type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: SADAD Reconciliation
  version: 1.0.0
  x-ibm-name: sadad-reconciliation
openapi: 3.0.0
paths:
  /sadad-reconciliation:
    post:
      operationId: SADADReconciliation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SADADReconciliationRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SADADReconciliationResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - SADADReconciliation
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://sadad-cut-off-http-bab-sit-cp4i.apps.babsitaro.albtests.com/SadadReconciliation
  testable: true
  type: rest
