components:
  schemas:
    RequestHeader:
      properties:
        backendReferenceNumber:
          type: string
        channelId:
          type: string
        cif:
          type: string
        deviceInfo:
          properties:
            city:
              type: string
            country:
              type: string
            id:
              type: string
            ipAddress:
              type: string
            model:
              type: string
            osType:
              type: string
            osVersion:
              type: string
          type: object
        frontendReferenceNumber:
          type: string
        functionId:
          type: string
        language:
          type: string
        messageFormat:
          type: string
        requesterInfo1:
          type: string
        requesterInfo2:
          type: string
        reversalOption:
          type: string
        segment:
          type: string
        transactionDateTime:
          type: string
      type: object
    ResponseHeader:
      allOf:
      - $ref: '#/components/schemas/RequestHeader'
      - properties:
          code:
            description: Response code
            type: string
          info:
            description: Response message
            type: string
        type: object
      type: object
    TransFastCreateTransactionRequest:
      additionalProperties: false
      properties:
        EAIMessage:
          additionalProperties: false
          description: Enterprise Application Integration envelope containing header
            metadata and business payload
          properties:
            Body:
              additionalProperties: false
              description: Business request payload specific to the service operation
              properties:
                Cmplnc:
                  additionalProperties: false
                  properties:
                    Cntry_Iss_Cd:
                      type: string
                    Funds_Src:
                      type: string
                    Rcvr_Fll_Nm:
                      type: string
                    Rcvr_Rltshp:
                      type: string
                    Sndr_Emplyr_Nm:
                      type: string
                  type: object
                Dbt_Acct_No:
                  type: string
                Rcvr:
                  additionalProperties: false
                  properties:
                    Ben_Cd:
                      type: string
                    Cntry_Cd:
                      type: string
                    Cty_Id:
                      type: string
                    Frst_Nm:
                      type: string
                    Is_Indvdl:
                      type: string
                    Lst_Nm:
                      type: string
                    Mbl_No:
                      type: string
                    Ntnlty_Cd:
                      type: string
                    Stt_Id:
                      type: string
                    Twn_Id:
                      type: string
                  type: object
                Sndr:
                  additionalProperties: false
                  properties:
                    Brth_Dt:
                      type: string
                    Cntry_Cd:
                      type: string
                    Id_Expry_Dt:
                      type: string
                    Id_No:
                      type: string
                    Id_Tp:
                      type: string
                    Is_Indvdl:
                      type: string
                    Mbl_No:
                      type: string
                    Nm:
                      type: string
                    Ntnlty_Cd:
                      type: string
                    Zp_Cd:
                      type: string
                  type: object
                Tmstmp:
                  type: string
                Trnsctn_Info:
                  additionalProperties: false
                  properties:
                    Bnk_Grss_Ttl_Amnt:
                      type: string
                    Bnk_Rcv_Amnt:
                      type: string
                    Bnk_Rt:
                      type: string
                    Bnk_Snt_Amnt:
                      type: string
                    Bnk_Srvc_Fee:
                      type: string
                    Bnk_Srvc_Fee_VAT_Amnt:
                      type: string
                    Bnk_Srvc_Fee_VAT_Prcntg:
                      type: string
                    Bnk_Ttl_Snt_Amnt:
                      type: string
                    Enjz_FX_Amnt:
                      type: string
                    Enjz_Fee_Amnt:
                      type: string
                    Pmnt_Md:
                      type: string
                    Prps_Of_Rmttnc_Id:
                      type: string
                    Pyng_Brnch_Id:
                      type: string
                    Pyr_Id:
                      type: string
                    Rcv_Amnt:
                      type: string
                    Rcv_Crrncy_Cd:
                      type: string
                    Rt:
                      type: string
                    SAMA_Prps_Of_Rmttnc_Id:
                      type: string
                    Snt_Amnt:
                      type: string
                    Src_Crrncy_Cd:
                      type: string
                    Srvc_Fee:
                      type: string
                    Sttlmnt_Rt:
                      type: string
                    TF_Fee_Amnt:
                      type: string
                    TF_Sttlmnt_Amnt_SAR:
                      type: string
                    TF_Sttlmnt_Amnt_USD:
                      type: string
                    Ttl_Bnk_Srvc_Fee:
                      type: string
                    Ttl_Snt_Amnt:
                      type: string
                  type: object
              type: object
            EAIHeader:
              additionalProperties: false
              description: Technical and routing metadata required for request processing
                and tracking
              properties:
                BE_Ref_No:
                  type: string
                CIF:
                  type: string
                ChnlId:
                  type: string
                EAIRtrnCd:
                  type: string
                FE_Ref_No:
                  type: string
                FunctnId:
                  type: string
                Lang:
                  type: string
                MsgFrmt:
                  type: string
                OrgnlMsgId:
                  type: string
                Rqstr_Info1:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info2:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info3:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info4:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info5:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info6:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info7:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info11:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info12:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info13:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info14:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info15:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info16:
                  description: Additional requester-provided metadata field
                  type: string
                Rqstr_Info19:
                  description: Additional requester-provided metadata field
                  type: string
                RvrslOptn:
                  type: string
                Tmstmp:
                  type: string
              type: object
          type: object
      type: object
    TransFastCreateTransactionResponse:
      properties:
        data:
          $ref: '#/components/schemas/TransFastCreateTransactionResponseData'
        result:
          $ref: '#/components/schemas/ResponseHeader'
      type: object
    TransFastCreateTransactionResponseData:
      description: Response data payload - customize per operation
      type: object
  securitySchemes:
    clientID:
      in: header
      name: X-IBM-Client-Id
      type: apiKey
      x-key-type: client_id
    clientSecret:
      in: header
      name: X-IBM-Client-Secret
      type: apiKey
      x-key-type: client_secret
    oAuth:
      flows:
        clientCredentials:
          scopes:
            Integration_scope: Integration_scope
          tokenUrl: https://$(catalog.url)/native-apic-oauth/oauth2/token
      type: oauth2
      x-ibm-oauth-provider: native-oauth-provider
info:
  title: TransFast Create Transaction
  version: 1.0.0
  x-ibm-name: transfast-create-transaction
openapi: 3.0.0
paths:
  /transfast-create-transaction:
    post:
      operationId: TransFastCreateTransaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransFastCreateTransactionRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransFastCreateTransactionResponse'
          description: success
security:
- clientID: []
  clientSecret: []
- oAuth:
  - Integration_scope
servers:
- url: /albilad-api/v1
x-ibm-configuration:
  activity-log:
    enabled: true
    error-content: payload
    success-content: activity
  assembly:
    execute:
    - operation-switch:
        case:
        - execute:
          - invoke:
              backend-type: json
              chunked-uploads: true
              follow-redirects: false
              header-control:
                type: blocklist
                values: []
              inject-proxy-headers: true
              parameter-control:
                type: allowlist
                values: []
              persistent-connection: true
              target-url: $(target-url)
              timeout: 60
              title: invoke
              verb: POST
              version: 2.0.0
          operations:
          - TransFastCreateTransaction
        otherwise: []
        title: operation-switch
        version: 2.0.0
  cors:
    enabled: false
  enforced: true
  gateway: datapower-api-gateway
  phase: realized
  properties:
    target-url:
      description: URL of the proxy policy
      encoded: false
      value: http://trans-fast-create-transaction-http-bab-sit-cp4i.apps.babsitaro.albtests.com/trans-fast-create-transaction
  testable: true
  type: rest
